Repository vital-software/scala-redox, pull requests merged in 2018-06, with the labels that each got.

#37 Fixes for grouped order parsing and optional Patient.Demographics.Sex field
  CHANGELOG.md
  src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
  src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
  src/test/scala/com/github/vitalsoftware/scalaredox/GroupedOrdersTest.scala
Labels: stage: review, type: bug

#39 Added FlowSheet data model
  src/main/scala/com/github/vitalsoftware/scalaredox/models/Common.scala
  src/main/scala/com/github/vitalsoftware/scalaredox/models/FlowSheetMessage.scala
  src/main/scala/com/github/vitalsoftware/scalaredox/models/VisitInfo.scala
  src/test/scala/com/github/vitalsoftware/scalaredox/FlowSheetTest.scala
  src/test/scala/com/github/vitalsoftware/scalaredox/NotesTest.scala
Labels: stage: in progress

#40 Add a HasVisitInfo trait
  CHANGELOG.md
  src/main/scala/com/github/vitalsoftware/scalaredox/models/Document.scala
  src/main/scala/com/github/vitalsoftware/scalaredox/models/HasVisitInfo.scala
  src/main/scala/com/github/vitalsoftware/scalaredox/models/Media.scala
  src/main/scala/com/github/vitalsoftware/scalaredox/models/Note.scala
  src/main/scala/com/github/vitalsoftware/scalaredox/models/Order.scala
  src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
  src/main/scala/com/github/vitalsoftware/scalaredox/models/Result.scala
Labels: stage: review

#41 Allow better pruning of subtrees that are empty
  CHANGELOG.md
  src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
  src/main/scala/com/github/vitalsoftware/util/JsonOps.scala
  src/test/scala/com/github/vitalsoftware/util/JsonOpsTest.scala
Labels: stage: review, type: enhancement

#42 Add a reducer argument to RedoxClient.webhook()
  CHANGELOG.md
  src/main/scala/com/github/vitalsoftware/scalaredox/client/RedoxClient.scala
Labels: stage: in progress, type: enhancement

#43 Perform Sonatype release correctly
  build.sbt
  project/plugins.sbt
Labels: stage: review, type: bug, type: devops

#44 Perform automated releases in CI
  .buildkite/pipeline.yml
  CHANGELOG.md
  build.sbt
  version.sbt
Labels: stage: in progress

#46 Per vital-software/api#938, rename "gender" to "sex".
  src/main/scala/com/github/vitalsoftware/scalaredox/models/FamilyHistory.scala
  src/main/scala/com/github/vitalsoftware/scalaredox/models/Patient.scala
  src/test/scala/com/github/vitalsoftware/scalaredox/ClinicalSummaryTest.scala
  src/test/scala/com/github/vitalsoftware/scalaredox/GroupedOrdersTest.scala
Labels: stage: in progress

#48 Upgrade to SBT 1.1
  build.sbt
  project/build.properties
  project/plugins.sbt
  version.sbt
Labels: stage: review, type: maintenance
